export const theme = {
	screenBackground: 'blue',
	tableBorder: 'yellow',
	tableText: 'yellow',
	activeColumnBackground: 'red',
	activeColumnText: 'yellow',
	cardBackground: 'white',
	cardBorder: 'white',
	cardTextBlack: 'black',
	cardTextRed: 'red',
	heldText: 'yellow',
	resultText: 'yellow',
	resultShadow: 'red',
	buttonBackground: 'yellow',
	buttonText: 'black',
	disabledButtonBackground: 'gray',
	disabledButtonText: 'gray',
	statusLabel: 'yellow',
	statusValue: 'white',
	secondaryText: 'white',
} as const;
